<script setup>
import CardItem from "@/components/CardItem.vue";

const cards = [
  {
    name: "Whiteboard Pen",
    price: 1.2,
    image: new URL("@/assets/whiteboard.jpg", import.meta.url).href,
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Simple Pen",
    price: 1.2,
    image: new URL("@/assets/slim.jpeg", import.meta.url).href,
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Screw",
    price: 0.2,
    image: new URL("@/assets/zipin.jpg", import.meta.url).href,
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Bolt",
    price: 0.5,
    image: new URL("@/assets/stainless.webp", import.meta.url).href,
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Customizable Desk",
    legs: "Custom",
    color: "White",
    price: 750.0,
    image: new URL("@/assets/par03-grey-frame_eyk_1.webp", import.meta.url)
      .href,
    colorLegs: "#C0E2C6",
    colorTextLegs: "#678E69",
    bgColor: "#9CD7D3",
    textColor: "#225A58",
  },
  {
    name: "Customizable Desk",
    legs: "Custom",
    color: "Black",
    colorLegs: "#C0E2C6",
    colorTextLegs: "#678E69",
    bgColor: "#E5DAFF",
    textColor: "#8F7EB3",
    price: 750.0,
    image: new URL("@/assets/par03-grey-frame_eyk_1.webp", import.meta.url),
  },
  {
    name: "Stool",
    color: "Dark Blue",
    price: 500.0,
    image: new URL("@/assets/f12a.webp", import.meta.url),
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "#9CD7D3",
    textColor: "#225A58",
  },
  {
    name: "Stool",
    color: "Green",
    price: 500.0,
    image: new URL("@/assets/f12a.webp", import.meta.url),
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "#E5DAFF",
    textColor: "#8F7EB3",
  },
  {
    name: "Stool",
    color: "Grey",
    price: 500.0,
    image: new URL("@/assets/f12a.webp", import.meta.url),
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "#E5DAFF",
    textColor: "#8F7EB3",
  },
  {
    name: "Corner Desk Right Sit",
    price: 147.0,
    image: new URL("@/assets/d3232.webp", import.meta.url),
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Large Cabinet",
    price: 320.0,
    image: new URL("@/assets/natural.jpg", import.meta.url),
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Storage Box",
    price: 15.8,
    image: new URL("@/assets/download.jpeg", import.meta.url),
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Large Desk",
    price: 1799.0,
    image: new URL("@/assets/51nYrPD-4ZL.jpg", import.meta.url),
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Pedal Bin",
    price: 47.0,
    image: new URL("@/assets/images.jpeg", import.meta.url),
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Cabinet with Doors",
    price: 140.0,
    image: new URL("@/assets/images (1).jpeg", import.meta.url),
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Conference Chair",
    legs: "Steel",
    price: 33.0,
    image: new URL("@/assets/Conference.png", import.meta.url),
    colorLegs: "#BDD3F1",
    colorTextLegs: "#3D5777",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Conference Chair",
    legs: "Aluminium",
    price: 39.4,
    image: new URL("@/assets/Conference.png", import.meta.url),
    colorLegs: "#99A9F6",
    colorTextLegs: "#202D6B",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Customized Cabinet (Metric)",
    price: 210.0,
    image: new URL("@/assets/images (1).jpeg", import.meta.url),
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Customized Cabinet (USA)",
    price: 200.0,
    image: new URL("@/assets/images (1).jpeg", import.meta.url),
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Expenses",
    price: 1.0,
    image: new URL("@/assets/images.png", import.meta.url),
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Desk Organizer",
    price: 5.1,
    image: new URL("@/assets/0775013_PE756791_S5.jpg", import.meta.url),
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Desk Pad",
    price: 1.98,
    image: new URL("@/assets/salgar-web.jpg", import.meta.url),
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
  {
    name: "LED Lamp",
    price: 0.9,

    image: new URL("@/assets/265285.webp", import.meta.url),
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Letter Tray",
    price: 4.8,

    image: new URL("@/assets/pigeon-holes-unit2.webp", import.meta.url),
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Magnetic Board",
    price: 1.98,
    image: new URL("@/assets/images (2).jpeg", import.meta.url),
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Monitor Stand",
    price: 3.19,
    image: new URL(
      "@/assets/sigfinn-monitor-stand-bamboo-veneer-ref-20362929.jpg",
      import.meta.url
    ),
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Newspaper Rack",
    price: 1.28,
    image: new URL("@/assets/31awX9IizHL.jpg", import.meta.url),
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
  {
    name: "Small Shelf",
    price: 2.83,
    image: new URL(
      "@/assets/39595c5d4e0649bbbe10e3c762eb7424.jpg",
      import.meta.url
    ),
    colorLegs: "",
    colorTextLegs: "",
    bgColor: "",
    textColor: "",
  },
];
</script>

<template>
  <div class="p-4 bg-slate-50 pt-28 lg:pt-16">
    <div
      class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-2"
    >
      <div v-for="(itemData, index) in cards" :key="index">
        <CardItem :itemData="itemData" />
      </div>
    </div>
  </div>
</template>
